notebook: update genfscon documentation
SELinuxProject/selinux-notebook pull request #22
Opened 2023-03-20 14:35 UTC by cgzones

Partial paths can be used generally for virtual kernel filesystems, e.g. cgroup2, securityfs, selinuxfs, and not just for the proc filesystem.

The genfscon statement supports an optional filetype specifier.

2023-07-27 13:29 UTC, stephensmalley reviewed
The situation is somewhat more complex than described here. See https://github.com/SELinuxProject/selinux-kernel/issues/2 for discussion of safety and use of genfscon. The kernel mechanism itself does not limit use of genfscon to only these cases; one can for example use it to label an initramfs-based rootfs, or a squashfs or even technically ext4 (but the latter wouldn't be safe).

2023-08-23 16:21 UTC, jbrindle commented
@cgzones Any chance you can publish an update to this based on Stephen's comment above, or would you prefer us to pick it up?

2023-08-30 12:16 UTC, cgzones commented
Updated the wording a bit, feel free to suggest improvements.

2023-08-30 14:09 UTC, stephensmalley approved these changes

2023-08-30 14:11 UTC, stephensmalley commented
Reviewed-by: Stephen Smalley <stephen.smalley.work@gmail.com>

2023-08-30 15:08 UTC, jbrindle requested changes

2023-08-30 15:08 UTC, jbrindle commented on src/file_labeling_statements.md
>  # it is a trusted process.
nit, it's a file, not process. It is s15 because it could contain data from any level on the system

2023-08-30 15:17 UTC, cgzones commented on src/file_labeling_statements.md
>  # it is a trusted process.
adjusted

2023-08-30 16:07 UTC, jbrindle commented
reviewed-by: Joshua Brindle <brindle@gmail.com>

2023-08-30 16:07 UTC, merged